name: unit test

on: [pull_request]

jobs:
  build:
    name: "run unit tests"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        include:
          - spark: 3.1.1
            java: 8
            hadoop: 3.2
            spark-major: "3.0"
          - spark: 2.4.3
            java: 8
            hadoop: 2.7
            spark-major: "2.4"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2

      - name: Install Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Install Spark ${{ matrix.spark }}
        uses: vemonet/setup-spark@v1
        with:
          spark-version: ${{ matrix.spark }}
          hadoop-version: ${{ matrix.hadoop }}

      # Run the tests.
      - name: Run tests
        run: ./dev/run-test.sh ${{ matrix.spark-major }}